### PR TITLE
feature - show queues 

### PR DESCRIPTION
**Pull request by mbobin**
Adds some new features:
- show number of jobs per queue in Overview
- reset queue filters

### CODE REVIEW

**Comment by andyatkinson** [comment]
@mbobin This seems straightforward. Can you confirm it's still safe to merge since a lot of time has passed. Also, could you document the "reset queue filters" change in the Readme as part of this change please? Thanks.

**Comment by mbobin** [comment]
@andyatkinson it's still safe.

**Comment by andyatkinson** [comment]
@mbobin I'll merge it this week. There are a couple other changes we could include in a new gem release. I'll make a new gem release as well and ping you.

**Comment by mbobin** [comment]
@andyatkinson, indeed there are. We could add support for Rails 5 and make sure it works with Ruby 2.4. Let me know if there is anything to do.

**Pull request merged**
