### PR TITLE
Adding a section for Heroku worker monitoring and zombie detection

### PR DESCRIPTION
**Pull request by hammady**
Adding a section to monitor heroku dynos in a table view.
Also sometimes when a heroku dyno dies and leaves the job locked, this PR will list those zombie jobs so that they can be requeued or cleared.
For the heroku integration to work, 2 environment variables need to be set:
`DJWEB_HEROKU_TOKEN` and `DJWEB_HEROKU_APP_NAME`
If any of these 2 are not found, the gem will work normally without heroku integration.

### CODE REVIEW

**Comment by andyatkinson** [comment]
@hammady Interesting. I'm not familiar with this. Since a lot of time has passed, is this something that's still beneficial and works on Heroku (and does Heroku work in the same way as when this was written?).  If you could re-test, can you also comment on whether this change might break outside of a Heroku environment. Finally, could you add some documentation about the environment variables, and a one-liner of detail about what the problem is, and how this solves it (you mostly covered it in the PR message, but it would be nice to have as Readme documentation for this project as well). Thanks.

**Comment by andyatkinson** [comment]
@hammady Is this still a thing you want to do? If not, I would close this PR. If I don't hear back from you, I'll assume this isn't something you'd like to pursue releasing (and supporting if there are issues). Thanks.

**Comment by hammady** [comment]
I was relying on this PR in production until last December and it was working on heroku. I believe it should still work. I will try to find some time soon to fulfill your request before merging.

**Comment by andyatkinson** [comment]
@hammady Oh ok. That seems fine then. Could you add a section to the Readme on your PR about what this does, and maybe the versions of Rails it was running in, and maybe some notes about the Heroku stack you're using? That way if someone wants to use it or has trouble with it, they have a better starting point to know how it was being used before.

**Pull request closed without merging**
